# The MIT License (MIT)
#
# Copyright (c) 2016-2020 Philippe Proulx <pproulx@efficios.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

%YAML 1.2
--- !<tag:barectf.org,2020/3/config>
trace:
  type:
    native-byte-order: little-endian
    $include:
      - stdint.yaml
      - stdreal.yaml
      - stdmisc.yaml
      - lttng-ust-log-levels.yaml
    $field-type-aliases:
      state:
        class: unsigned-enumeration
        size: 8
        mappings:
          NEW: [0]
          TERMINATED: [1]
          READY: [2]
          RUNNING: [3]
          WAITING: [4]
    clock-types:
      default:
        $c-type: uint64_t
    data-stream-types:
      default:
        $is-default: true
        $default-clock-type-name: default
        event-record-types:
          simple_uint32:
            log-level: CRIT
            payload-field-type:
              class: structure
              members:
                - value: uint32
          simple_int16:
            payload-field-type:
              class: structure
              members:
                - value: int16
          simple_float:
            payload-field-type:
              class: structure
              members:
                - value: float
          simple_string:
            log-level: WARNING
            payload-field-type:
              class: structure
              members:
                - value: string
          simple_enum:
            payload-field-type:
              class: structure
              members:
                - value: state
          context_no_payload:
            specific-context-field-type:
              class: structure
              members:
                - a: uint32
                - b: string
          no_context_no_payload: {}
          a_few_fields:
            payload-field-type:
              class: structure
              members:
                - int32: int32
                - uint16: uint16
                - dbl: double
                - str: string
                - state: state
          bit_packed_integers:
            log-level: 513
            payload-field-type:
              class: structure
              members:
                - uint1:
                    field-type:
                      $inherit: bit-packed-uint8
                      size: 1
                - int1:
                    field-type:
                      $inherit: bit-packed-int8
                      size: 1
                - uint2:
                    field-type:
                      $inherit: bit-packed-uint8
                      size: 2
                - int3:
                    field-type:
                      $inherit: bit-packed-int8
                      size: 3
                - uint4:
                    field-type:
                      $inherit: bit-packed-uint8
                      size: 4
                - int5:
                    field-type:
                      $inherit: bit-packed-int8
                      size: 5
                - uint6:
                    field-type:
                      $inherit: bit-packed-uint8
                      size: 6
                - int7:
                    field-type:
                      $inherit: bit-packed-int8
                      size: 7
                - uint8: bit-packed-uint8
